# Copyright 2026 Anthropic PBC
# SPDX-License-Identifier: Apache-2.0
# Minimal single-node kind cluster for the demo workload in workload.yaml.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: managed-agent-demo
nodes:
  - role: control-plane
